name: New-release

on:
  push:
    tags:
      - 'v*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#      - name: Debugging with tmate
#        uses: mxschmitt/action-tmate@v3.14

      - name: Commit the new tag to the config folder
        run: |
          echo "Write new release into pmb.yml"
          sed -i 's/APP_VERSION.*/APP_VERSION: '"${{ github.event.inputs.tag }}"'/g' config/pmb.yaml
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 'master'
          file_pattern: 'config/pmb.yaml'

#      - name: Notify about this change via Slack
#        uses: 8398a7/action-slack@v2
#        with:
#          status: ${{ job.status }}
#          author_name: 'Triggered by - @${{ github.actor }}'
#          text: ${{ github.actor }}
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_V1 }} # required
#        if: always()
