name: New-release

on:
  push:
    branches:
      - 'release-**'

env:
  VERSION:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{github.ref_name }} | cut -d'-' -f 2

      - name: Commit the new tag to the config folder
        run: |
          echo "Write new release into pmb.yml"
          version=$( echo ${{ github.ref_name }} | cut -d'-' -f 2); sed -i 's/APP_VERSION.*/APP_VERSION: '"$version"'/g' config/pmb.yaml

      #      - name: Debugging with tmate
      #        uses: mxschmitt/action-tmate@v3.14


      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'config/pmb.yaml'

#      - name: Notify about this change via Slack
#        uses: 8398a7/action-slack@v2
#        with:
#          status: ${{ job.status }}
#          author_name: 'Triggered by - @${{ github.actor }}'
#          text: ${{ github.actor }}
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_V1 }} # required
#        if: always()
