name: New-release

on:
  push:
    tags:
      - 'v*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.14

      - name: Commit the new tag to the config folder
        run: |
          echo "Write new release into pmb.yml"
          sed -i 's/APP_VERSION.*/APP_VERSION: '"${{ github.event.inputs.tag }}"'/g' config/pmb.yaml
          git config --global user.name 'RH DevBot'
          git config --global user.email 'noreply@rectanglehealth.com'
          git commit -am "Update app version"
          git push

      - name: Update Master with the new release
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update Master with new release
          committer: GitHub <devbot@rectanglehealth.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
#      - name: Notify about this change via Slack
#        uses: 8398a7/action-slack@v2
#        with:
#          status: ${{ job.status }}
#          author_name: 'Triggered by - @${{ github.actor }}'
#          text: ${{ github.actor }}
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_V1 }} # required
#        if: always()
